version: 2
jobs:
  test:
    docker:
      - image: docker:stable-git
    working_directory: /code
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build -t paper_trail .
      - deploy:
          name: Push application Docker image
          command: |
            DOCKER_TAG=$(echo paper_trail:${CIRCLE_BRANCH} | tr '/' '_')
            DOCKER_TARGET_REMOTE="${HUB_USERNAME}/${DOCKER_TAG}"
            echo $HUB_KEY | docker login -u $HUB_USERNAME --password-stdin
            docker tag paper_trail "${DOCKER_TARGET_REMOTE}"
            docker push "${DOCKER_TARGET_REMOTE}"
      - run:
          name: Pull and run a docker container
          command: |
            apk add docker-compose
            sed -i $(echo "s/\$CIRCLE_BRANCH/$CIRCLE_BRANCH/g") /code/.env
      - run: docker-compose run backend mix test test/paper_trail
      - run: docker-compose run backend mix test test/version
      - run: docker-compose run backend mix test test/uuid

workflows:
  version: 2
  build_and_test:
    jobs:
      - test

# https://circleci.com/blog/how-to-build-a-docker-image-on-circleci-2-0/
